[package]
name = "session-tyorka-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "=7.2"
tokio = { version = "0.2", features = ["macros", "rt-threaded", "sync", "time"] }
warp = "0.2"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
chrono = "0.4"
actix-rt = "1.1.0"
actix-web = "3.0.0-alpha.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
env_logger = "0.7.1"
confy = "0.3.1"
log = "0.4.17"
rand = "0.5.0"
derive_more = "0.99.17"
reqwest = { version = "0.11", features = ["json"] }
cached = "0.36.0"
base64 = "0.13.0"
time = "0.2.27"

